FROM node:10.16.1 AS service
COPY source/. src/
WORKDIR /src
ENV MEMORY 1024
ENV DATABASE_HOSTNAME otus-database
ENV DATABASE_PORT 27017
ENV ELASTICSEARCH_HOSTNAME elasticsearch
ENV ELASTICSEARCH_PORT 9200
ENV DATABASE_USER communication
ENV DATABASE_PASS communication
ENV DATABASE otus-communication
ENV API_PORT 8080
ENV MAILER_FROM MAILER_FROM
ENV MAILER_HOST MAILER_HOST
ENV MAILER_PORT MAILER_PORT
ENV MAILER_SECURE MAILER_SECURE
ENV MAILER_SERVICE ''
ENV MAILER_AUTH_USER MAILER_AUTH_USER
ENV MAILER_AUTH_PASS MAILER_AUTH_PASS
ENV CONFIG_READY CONFIG_READY
ENV PROTOCOL PROTOCOL
CMD node --max-old-space-size=$MEMORY --optimize-for-size app.js
